### ISSUE TITLE
scripts/build fails

### ISSUE THREAD

**Issue by msorc** [kennytilton/spamux#1]
``` sh
# lein -v
Leiningen 2.8.1 on Java 1.8.0_161 OpenJDK 64-Bit Server VM```

``` sh
# scripts/build

Reading analysis cache for jar:file:~/.m2/repository/com/tiltontec/xhr/0.1.1-SNAPSHOT/xhr-0.1.1-SNAPSHOT.jar!/tiltontec/xhr.cljc
Exception in thread "main" clojure.lang.ExceptionInfo: failed compiling file:src/spamux/component.cljs {:file #object[java.io.File 0x4daf8e98 "src/spamux/component.cljs"]}, compiling:(clojure/spammer/resources/spamux/scripts/build.clj:5:1)
        at clojure.lang.Compiler.load(Compiler.java:7526)
        at clojure.lang.Compiler.loadFile(Compiler.java:7452)
        at clojure.main$load_script.invokeStatic(main.clj:278)
        at clojure.main$script_opt.invokeStatic(main.clj:338)
        at clojure.main$script_opt.invoke(main.clj:333)
        at clojure.main$main.invokeStatic(main.clj:424)
        at clojure.main$main.doInvoke(main.clj:387)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.main.main(main.java:37)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
        at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
        at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
        at user$eval149.invokeStatic(form-init63471864932030423.clj:1)
        at user$eval149.invoke(form-init63471864932030423.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7062)
        at clojure.lang.Compiler.eval(Compiler.java:7052)
        at clojure.lang.Compiler.load(Compiler.java:7514)
        at clojure.lang.Compiler.loadFile(Compiler.java:7452)
        at clojure.main$load_script.invokeStatic(main.clj:278)
        at clojure.main$init_opt.invokeStatic(main.clj:280)
        at clojure.main$init_opt.invoke(main.clj:280)
        at clojure.main$initialize.invokeStatic(main.clj:311)
        at clojure.main$null_opt.invokeStatic(main.clj:345)
        at clojure.main$null_opt.invoke(main.clj:342)
        at clojure.main$main.invokeStatic(main.clj:424)
        at clojure.main$main.doInvoke(main.clj:387)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: failed compiling file:src/spamux/component.cljs {:file #object[java.io.File 0x4daf8e98 "src/spamux/component.cljs"]}
        at clojure.core$ex_info.invokeStatic(core.clj:4739)
        at clojure.core$ex_info.invoke(core.clj:4739)
        at cljs.compiler$compile_file$fn__4734.invoke(compiler.cljc:1552)
        at cljs.compiler$compile_file.invokeStatic(compiler.cljc:1513)
        at cljs.compiler$compile_file.invoke(compiler.cljc:1489)
        at cljs.closure$compile_file.invokeStatic(closure.clj:540)
        at cljs.closure$compile_file.invoke(closure.clj:531)
        at cljs.closure$eval6989$fn__6990.invoke(closure.clj:609)
        at cljs.closure$eval6925$fn__6926$G__6914__6933.invoke(closure.clj:493)
        at cljs.closure$compile_sources$iter__7113__7117$fn__7118.invoke(closure.clj:954)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.RT.next(RT.java:706)
        at clojure.core$next__5108.invokeStatic(core.clj:64)
        at clojure.core$dorun.invokeStatic(core.clj:3134)
        at clojure.core$doall.invokeStatic(core.clj:3140)
        at clojure.core$doall.invoke(core.clj:3140)
        at cljs.closure$compile_sources.invokeStatic(closure.clj:950)
        at cljs.closure$compile_sources.invoke(closure.clj:939)
        at cljs.closure$build.invokeStatic(closure.clj:2596)
        at cljs.closure$build.invoke(closure.clj:2507)
        at cljs.build.api$build.invokeStatic(api.clj:205)
        at cljs.build.api$build.invoke(api.clj:189)
        at cljs.build.api$build.invokeStatic(api.clj:192)
        at cljs.build.api$build.invoke(api.clj:189)
        at user$eval7918.invokeStatic(build.clj:6)
        at user$eval7918.invoke(build.clj:5)
        at clojure.lang.Compiler.eval(Compiler.java:7062)
        at clojure.lang.Compiler.load(Compiler.java:7514)
        ... 38 more
Caused by: clojure.lang.ExceptionInfo: No such namespace: tiltontec.webmx.gen, could not locate tiltontec/webmx/gen.cljs, tiltontec/webmx/gen.cljc, or JavaScript source providing "tiltontec.webmx.gen" in file src/spamux/component.cljs {:tag :cljs/analysis-error}
        at clojure.core$ex_info.invokeStatic(core.clj:4739)
        at clojure.core$ex_info.invoke(core.clj:4739)
        at cljs.analyzer$error.invokeStatic(analyzer.cljc:697)
        at cljs.analyzer$error.invoke(analyzer.cljc:693)
        at cljs.analyzer$error.invokeStatic(analyzer.cljc:695)
        at cljs.analyzer$error.invoke(analyzer.cljc:693)
        at cljs.analyzer$analyze_deps.invokeStatic(analyzer.cljc:2128)
        at cljs.analyzer$analyze_deps.invoke(analyzer.cljc:2102)
        at cljs.analyzer$ns_side_effects.invokeStatic(analyzer.cljc:3467)
        at cljs.analyzer$ns_side_effects.invoke(analyzer.cljc:3462)
        at cljs.analyzer$analyze_STAR_$fn__3445.invoke(analyzer.cljc:3586)
        at clojure.lang.PersistentVector.reduce(PersistentVector.java:341)
        at clojure.core$reduce.invokeStatic(core.clj:6747)
        at clojure.core$reduce.invoke(core.clj:6730)
        at cljs.analyzer$analyze_STAR_.invokeStatic(analyzer.cljc:3586)
        at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:3576)
        at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3610)
        at cljs.analyzer$analyze.invoke(analyzer.cljc:3593)
        at cljs.compiler$emit_source.invokeStatic(compiler.cljc:1377)
        at cljs.compiler$emit_source.invoke(compiler.cljc:1356)
        at cljs.compiler$compile_file_STAR_$fn__4703.invoke(compiler.cljc:1456)
        at cljs.compiler$with_core_cljs.invokeStatic(compiler.cljc:1271)
        at cljs.compiler$with_core_cljs.invoke(compiler.cljc:1260)
        at cljs.compiler$compile_file_STAR_.invokeStatic(compiler.cljc:1441)
        at cljs.compiler$compile_file_STAR_.invoke(compiler.cljc:1434)
        at cljs.compiler$compile_file$fn__4734.invoke(compiler.cljc:1538)
        ... 65 more
```

**Comment by kennytilton** [comment]
Oops, I was getting by thanks to checkouts pointing to apparently undeployed stuff. I have recreated your error and will let you know when the coast is clear. Thx.

**Comment by kennytilton** [comment]
Hmm, I was also not requiring webmx in the project. I do not believe checkouts is a workaround. Matrix had webmx included for a while, maybe I was hitting it there. Anyway, I just retested from a fresh repo clean snd you should be OK. After you pull (a) the checkouts dir spamme/resources/spamux/checkouts should be gone and the spamux.prj should include a require of webmx.

**Comment by msorc** [comment]
Still no success:
``` sh
scripts/build 
Building ...
Exception in thread "main" clojure.lang.ExceptionInfo: Only :as, :refer and :rename options supported in :require / :require-macros; offending spec: [tiltontec.model.core :require [make] :as md] at line 1 src/spamux/job.cljs {:file #object[java.io.File 0x28a33dc9 "src/spamux/job.cljs"], :line 1, :column 1, :tag :cljs/analysis-error}, compiling:(spammer/resources/spamux/scripts/build.clj:5:1)
        at clojure.lang.Compiler.load(Compiler.java:7526)
        ....
Caused by: clojure.lang.ExceptionInfo: Only :as, :refer and :rename options supported in :require / :require-macros; offending spec: [tiltontec.model.core :require [make] :as md] at line 1 src/spamux/job.cljs {:file #object[java.io.File 0x28a33dc9 "src/spamux/job.cljs"], :line 1, :column 1, :tag :cljs/analysis-error}
        at clojure.core$ex_info.invokeStatic(core.clj:4739)
        ......```

**Comment by kennytilton** [comment]
Sorry, I better stop coding on master. I will clean up and let you know when I have retested.

**Comment by kennytilton** [comment]
Ugh, that was a big commit against master right in the middle of an upheaval that will take until tomorrow to complete. I just tested a new branch created from the prior commit and it looks good:

git checkout lastgood

Sorry again.

**Comment by msorc** [comment]
Works now, was able to start and get a web page running.

**Comment by kennytilton** [comment]
Thanks for your persistence! Let me know if you need doc or anything or just have questions. I have a major overhaul going on to hide the XHR juggling where I see common patterns. Hopefully tomorrow it will look a lot simpler.
